<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NBAOTUAN-PC" name="Articles.TM_JOOMLA_ARTICLE_001" tests="7" failures="1" timestamp="31 Dec 2015 19:00:11 GMT" time="249.909" errors="0">
  <testcase name="TC_JOOMLA_ARTICLE_001" time="72.152" classname="Articles.TM_JOOMLA_ARTICLE_001"/>
  <testcase name="TC_JOOMLA_ARTICLE_015" time="37.316" classname="Articles.TM_JOOMLA_ARTICLE_001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at ac_common.CommonElements.verifyTrue(CommonElements.java:123)
	at Articles.TM_JOOMLA_ARTICLE_001.TC_JOOMLA_ARTICLE_015(TM_JOOMLA_ARTICLE_001.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- TC_JOOMLA_ARTICLE_015 -->
  <testcase name="TC_JOOMLA_ARTICLE_007" time="29.554" classname="Articles.TM_JOOMLA_ARTICLE_001"/>
  <testcase name="TC_JOOMLA_ARTICLE_004" time="14.229" classname="Articles.TM_JOOMLA_ARTICLE_001"/>
  <testcase name="TC_JOOMLA_ARTICLE_003" time="14.294" classname="Articles.TM_JOOMLA_ARTICLE_001"/>
  <testcase name="TC_JOOMLA_ARTICLE_005" time="30.920" classname="Articles.TM_JOOMLA_ARTICLE_001"/>
  <testcase name="TC_JOOMLA_ARTICLE_002" time="51.444" classname="Articles.TM_JOOMLA_ARTICLE_001"/>
</testsuite> <!-- Articles.TM_JOOMLA_ARTICLE_001 -->
